import test from 'node:test'
import assert from 'node:assert/strict'
import { jsPDF } from 'jspdf'
import { buildTeacherTimetable } from '../src/teacher-timetable.ts'
import {
  buildTeacherExportPayload,
  createTeacherExportXmp,
  embedTeacherMetadataInJpeg,
  embedTeacherMetadataInPng,
  extractTeacherMetadataFromJpeg,
  extractTeacherMetadataFromPng,
  extractTeacherMetadataFromXmp,
  verifyTeacherExportPayload,
} from '../src/teacher-export-metadata.ts'

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
const cell = (teacherId, itemId, abbreviation, name) => ({
  teacherId, itemId, code: 'CSE501', abbreviation, name, kind: 'core',
})
const section = (sectionId, schedule) => ({
  sectionId,
  schedule: Object.fromEntries(days.map((day) => [day, { ...(schedule[day] ?? {}) }])),
})
const setupFor = (department) => ({
  academic: { department, academicYear: '2026 - 2027', year: 'III / 3rd Year', semester: 'V / 5th Semester' },
  staff: [{ id: `${department.toLowerCase()}-teacher-1`, name: `${department} Teacher` }],
})

function minimalPng() {
  return Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130])
}

test('CSE and MECH teacher payloads fingerprint actual global generation and assignments', async () => {
  for (const department of ['CSE', 'MECH']) {
    const setup = setupFor(department)
    const teacher = setup.staff[0]
    const generated = [
      section('A', { Monday: { 3: cell(teacher.id, 'core:cn', 'CN', 'Computer Networks') } }),
      section('B', { Tuesday: { 5: cell('someone-else', 'core:dbs', 'DBS', 'Database Systems') } }),
    ]
    const timetable = buildTeacherTimetable(generated, teacher.id)
    const payload = await buildTeacherExportPayload({ setup, teacher, generatedSections: generated, timetable, exportedAt: '2026-09-27T00:00:00.000Z', exportId: `${department}-export-1` })

    assert.equal(payload.generator.id, 'mvit-college-timetable-generator')
    assert.equal(payload.originMarker, 'This file was generated by the College Timetable Generator.')
    assert.equal(payload.sourceType, 'Teacher-wise Timetable')
    assert.equal(payload.teacherId, teacher.id)
    assert.equal(payload.teacherName, teacher.name)
    assert.equal(payload.departmentId, department)
    assert.equal(payload.departmentName, department === 'CSE' ? 'Computer Science & Engineering' : 'Mechanical Engineering')
    assert.equal(payload.academicYear, '2026-2027')
    assert.equal(payload.year, '3rd Year')
    assert.equal(payload.semester, 'Odd')
    assert.deepEqual(payload.sectionList, ['A', 'B'])
    assert.deepEqual(payload.assignments.map(({ day, period, section, abbreviation, teacherId }) => [day, period, section, abbreviation, teacherId]), [
      ['Monday', 3, 'A', 'CN', teacher.id],
    ])
    assert.match(payload.generationId, /^sha256:[a-f0-9]{64}$/)
    assert.equal(await verifyTeacherExportPayload(payload), true)
    assert.equal(await verifyTeacherExportPayload({ ...payload, assignments: [] }), false)
  }
})

test('PDF XMP packet carries the same machine-readable teacher schedule payload', async () => {
  const setup = setupFor('CSE')
  const teacher = setup.staff[0]
  const generated = [section('A', { Monday: { 3: cell(teacher.id, 'core:cn', 'CN', 'Computer Networks') } })]
  const payload = await buildTeacherExportPayload({ setup, teacher, generatedSections: generated, timetable: buildTeacherTimetable(generated, teacher.id), exportId: 'pdf-export' })
  const recovered = extractTeacherMetadataFromXmp(createTeacherExportXmp(payload))
  assert.deepEqual(recovered, payload)

  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4', compress: true })
  pdf.setProperties({ title: `Teacher-wise Timetable - ${payload.teacherName}`, author: payload.teacherName, creator: payload.generator.id })
  pdf.addMetadata(createTeacherExportXmp(payload), true)
  const pdfBytes = new Uint8Array(await pdf.output('arraybuffer'))
  const pdfText = new TextDecoder('latin1').decode(pdfBytes)
  const xmpStart = pdfText.indexOf('<x:xmpmeta')
  const xmpEnd = pdfText.indexOf('</x:xmpmeta>', xmpStart) + '</x:xmpmeta>'.length
  assert.ok(xmpStart >= 0 && xmpEnd > xmpStart, 'PDF should contain embedded XMP metadata')
  assert.deepEqual(extractTeacherMetadataFromXmp(pdfText.slice(xmpStart, xmpEnd)), payload)
})

test('PNG textual chunk and JPEG XMP embed and recover identical validated payloads', async () => {
  const setup = setupFor('MECH')
  const teacher = setup.staff[0]
  const generated = [section('A', { Wednesday: { 6: cell(teacher.id, 'core:rccm', 'RCCM', 'Refrigeration and Cold Chain Management') } })]
  const payload = await buildTeacherExportPayload({ setup, teacher, generatedSections: generated, timetable: buildTeacherTimetable(generated, teacher.id), exportId: 'image-export' })

  const sourcePng = minimalPng()
  const sourceJpeg = Uint8Array.from([0xff, 0xd8, 0xff, 0xd9])
  const png = embedTeacherMetadataInPng(sourcePng, payload)
  const jpeg = embedTeacherMetadataInJpeg(sourceJpeg, payload)
  assert.deepEqual(extractTeacherMetadataFromPng(png), payload)
  assert.deepEqual(extractTeacherMetadataFromJpeg(jpeg), payload)
  assert.deepEqual(png.subarray(0, 8), sourcePng.subarray(0, 8))
  assert.deepEqual(png.subarray(-12), sourcePng.subarray(-12))
  assert.deepEqual(jpeg.subarray(0, 2), sourceJpeg.subarray(0, 2))
  const jpegSegmentLength = (jpeg[4] << 8) | jpeg[5]
  assert.deepEqual(jpeg.subarray(4 + jpegSegmentLength), sourceJpeg.subarray(2))
  assert.equal(await verifyTeacherExportPayload(extractTeacherMetadataFromPng(png)), true)
  const damagedPng = png.slice()
  damagedPng[30] ^= 1
  assert.throws(() => extractTeacherMetadataFromPng(damagedPng), /checksum|damaged/i)
})
