import {
  extractTeacherMetadataFromJpeg,
  extractTeacherMetadataFromPdf,
  extractTeacherMetadataFromPng,
  teacherExportSourceKey,
  validateTeacherExportPayload,
  type TeacherExportPayload,
} from './teacher-export-metadata.ts'

export type ConsolidatedUploadType = 'PDF' | 'PNG' | 'JPG' | 'Unsupported'
export type ConsolidatedUploadStatus = 'pending' | 'valid' | 'rejected'

export interface ConsolidatedUploadItem {
  id: string
  file: File
  fileType: ConsolidatedUploadType
  status: ConsolidatedUploadStatus
  payload?: TeacherExportPayload
  rejectionReason?: string
}

type UploadFile = Pick<File, 'name' | 'type'>

const mimeByType: Record<Exclude<ConsolidatedUploadType, 'Unsupported'>, string[]> = {
  PDF: ['application/pdf'],
  PNG: ['image/png'],
  JPG: ['image/jpeg'],
}

const unsupportedFormatReason = 'Upload rejected: Unsupported file format. Please upload a PDF, PNG or JPG Teacher-wise Timetable generated by this application.'
const scopeRejectionPrefix = 'Upload rejected: '
const readErrorForType: Record<Exclude<ConsolidatedUploadType, 'Unsupported'>, string> = {
  PDF: 'Upload rejected: PDF could not be read.',
  PNG: 'Upload rejected: PNG could not be read.',
  JPG: 'Upload rejected: JPG could not be read.',
}

export function getConsolidatedUploadType(file: UploadFile): Exclude<ConsolidatedUploadType, 'Unsupported'> | null {
  const extension = file.name.split('.').at(-1)?.toLowerCase()
  const type = extension === 'pdf'
    ? 'PDF'
    : extension === 'png'
      ? 'PNG'
      : extension === 'jpg' || extension === 'jpeg'
        ? 'JPG'
        : null
  if (!type) return null
  const mimeType = file.type.toLowerCase()
  return !mimeType || mimeByType[type].includes(mimeType) ? type : null
}

export function createConsolidatedUploadItem(file: File, id: string): ConsolidatedUploadItem {
  const fileType = getConsolidatedUploadType(file)
  return fileType
    ? { id, file, fileType, status: 'pending' }
    : { id, file, fileType: 'Unsupported', status: 'rejected', rejectionReason: unsupportedFormatReason }
}

export async function validateConsolidatedUpload(item: ConsolidatedUploadItem): Promise<ConsolidatedUploadItem> {
  if (item.fileType === 'Unsupported') return item
  let bytes: Uint8Array
  try {
    bytes = new Uint8Array(await item.file.arrayBuffer())
  } catch {
    return { ...item, status: 'rejected', rejectionReason: readErrorForType[item.fileType] }
  }

  let payload: TeacherExportPayload | null
  try {
    payload = item.fileType === 'PDF'
      ? extractTeacherMetadataFromPdf(bytes)
      : item.fileType === 'PNG'
        ? extractTeacherMetadataFromPng(bytes)
        : extractTeacherMetadataFromJpeg(bytes)
  } catch (error) {
    const message = error instanceof Error ? error.message : ''
    const rejectionReason = /metadata/i.test(message)
      ? 'Upload rejected: Timetable metadata is malformed or invalid.'
      : readErrorForType[item.fileType]
    return { ...item, status: 'rejected', rejectionReason }
  }
  if (!payload) {
    return {
      ...item,
      status: 'rejected',
      rejectionReason: 'Upload rejected: This file is not a Teacher-wise Timetable generated by the application; required timetable metadata is missing.',
    }
  }

  if (item.fileType !== 'PDF' && typeof createImageBitmap === 'function') {
    try {
      const bitmap = await createImageBitmap(item.file)
      bitmap.close()
    } catch {
      return { ...item, status: 'rejected', payload, rejectionReason: readErrorForType[item.fileType] }
    }
  }

  const validation = await validateTeacherExportPayload(payload)
  if (!validation.valid) {
    return { ...item, status: 'rejected', payload, rejectionReason: `Upload rejected: ${validation.reason}` }
  }
  return { ...item, status: 'valid', payload: validation.payload }
}

export function validateConsolidationScope(
  item: ConsolidatedUploadItem,
  acceptedItems: ConsolidatedUploadItem[],
): ConsolidatedUploadItem {
  if (item.status !== 'valid' || !item.payload) return item
  const target = acceptedItems.find((candidate) => candidate.status === 'valid' && candidate.payload)
  if (!target?.payload) return item

  const found = item.payload
  const expected = target.payload
  if (found.teacherId !== expected.teacherId) {
    return {
      ...item,
      status: 'rejected',
      rejectionReason: `Upload rejected: Teacher mismatch. This file belongs to ${found.teacherName}, but the current consolidation is for ${expected.teacherName}.`,
    }
  }
  if (acceptedItems.some((candidate) => candidate.status === 'valid' && candidate.payload
    && teacherExportSourceKey(candidate.payload) === teacherExportSourceKey(found))) {
    return {
      ...item,
      status: 'rejected',
      rejectionReason: 'Upload rejected: This timetable source is already included.',
    }
  }
  return item
}

export function canGenerateTogether(items: ConsolidatedUploadItem[]): boolean {
  if (items.length < 2 || items.some((item) => item.status !== 'valid' || !item.payload)) return false

  const accepted: ConsolidatedUploadItem[] = []
  for (const item of items) {
    const scoped = validateConsolidationScope(item, accepted)
    if (scoped.status !== 'valid') return false
    accepted.push(scoped)
  }
  return true
}

export function removeConsolidatedUploadItem(items: ConsolidatedUploadItem[], id: string): ConsolidatedUploadItem[] {
  const remaining = items.filter((item) => item.id !== id).map((item) => {
    const isScopeRejection = item.status === 'rejected' && item.payload &&
      (item.rejectionReason?.startsWith(`${scopeRejectionPrefix}Teacher mismatch.`) ||
        item.rejectionReason?.startsWith(`${scopeRejectionPrefix}This timetable source is already included.`))
    return isScopeRejection ? { ...item, status: 'valid' as const, rejectionReason: undefined } : item
  })

  const accepted: ConsolidatedUploadItem[] = []
  return remaining.map((item) => {
    if (item.status !== 'valid' || !item.payload) return item
    const scoped = validateConsolidationScope(item, accepted)
    if (scoped.status === 'valid') accepted.push(scoped)
    return scoped
  })
}
