import type { StaffMember } from './models'

/**
 * Stable IDs for staff members explicitly identified as the same person across
 * department source data. Reuse these IDs in each department's local Staff list.
 */
export const globalStaffIds = {
  drAMathiarasu: 'ST029',
  drPNatarajan: 'ST030',
} as const

export const globalStaffMaster: StaffMember[] = [
  { id: 'ST001', name: 'Mrs. Elakkiya' },
  { id: 'ST002', name: 'Dr. J. Vaishnavi' },
  { id: 'ST003', name: 'Mrs. R. Indumathi' },
  { id: 'ST004', name: 'Mr. Kameshwaran' },
  { id: 'ST005', name: 'Mr. Kamaleshwaran' },
  { id: 'ST006', name: 'Miss. A. Suganthi' },
  { id: 'ST007', name: 'Mrs. S. Boovaneswari' },
  { id: 'ST008', name: 'Mrs. J. Jayapradha' },
  { id: 'ST009', name: 'Mr. Kishore' },
  { id: 'ST010', name: 'Mrs. G. Sharmila' },
  { id: 'ST011', name: 'Mrs. M. Subashree' },
  { id: 'ST012', name: 'Mr. V. Mohan' },
  { id: 'ST013', name: 'Mrs. D. Mohana Priya' },
  { id: 'ST014', name: 'Mr. Jayson' },
  { id: 'ST015', name: 'Mrs. Sheelarani' },
  { id: 'ST016', name: 'Mrs. Sathyavani' },
  { id: 'ST017', name: 'Mr. L. Vimal Raj' },
  { id: 'ST018', name: 'Mr. R. Sathishkumar' },
  { id: 'ST019', name: 'Mr. N. Arikaran' },
  { id: 'ST020', name: 'Mrs. Kalpana' },
  { id: 'ST021', name: 'Mrs. Devanadhan' },
  { id: 'ST022', name: 'Mr. R. Sathyamoorthy' },
  { id: 'ST023', name: 'Mrs. R. Athivaishnavi' },
  { id: 'ST024', name: 'Mrs. Nandhini' },
  { id: 'ST025', name: 'Mrs. D. Devaki' },
  { id: 'ST026', name: 'Mrs. U. R. Padma' },
  { id: 'ST027', name: 'Mr. B. Vasanth' },
  { id: 'ST028', name: 'Mr. A. Thiagarajan' },
  { id: 'ST029', name: 'Dr. A. Mathiarasu' },
  { id: 'ST030', name: 'Dr. P. Natarajan' },
  { id: 'ST031', name: 'Mrs. G. Deeba' },
  { id: 'ST032', name: 'Mr. K. Selvam' },
  { id: 'ST033', name: 'Dr. R. Rajalakshmi' },
  { id: 'ST034', name: 'Mr. G. Nandhakumar' },
  { id: 'ST035', name: 'Mrs. V. Vimala Dheekshanya' },
  { id: 'ST036', name: 'Dr. A. Meiyappane' },
  { id: 'ST037', name: 'Mr. Boobalan' },
  { id: 'ST038', name: 'Mr. Sriman Narayanan' },
  { id: 'ST039', name: 'MBA Staff' },
  { id: 'ST040', name: 'Mrs. K. Jagadheeswari' },
  { id: 'ST041', name: 'Mrs. D. Sudha' },
  { id: 'ST042', name: 'Mrs. B. V. Saranya' },
  { id: 'ST043', name: 'Mrs. K. Rajasi' },
  { id: 'ST044', name: 'Mrs. R. Priya' },
  { id: 'ST045', name: 'Mrs. V. Niraimathi' },
  { id: 'ST046', name: 'Mrs. S. K. Sugnedham' },
  { id: 'ST047', name: 'Mr. S. Balaji' },
  { id: 'ST048', name: 'Mrs. Radha' },
  { id: 'ST049', name: 'Ms. K. Revathy' },
  { id: 'ST050', name: 'All Faculty' },
  { id: 'ST051', name: 'Dr. R. Sofia' },
  { id: 'ST052', name: 'Mr. C. Jeeva Saravanan' },
  { id: 'ST053', name: 'Mr. C. Thiagarajan' },
  { id: 'ST054', name: 'Mrs. Zarina Begum' },
  { id: 'ST055', name: 'Mrs. K. Alamelu' },
  { id: 'ST056', name: 'Mr. V. Rajesh' },
  { id: 'ST057', name: 'Mr. S. Mohanraj' },
  { id: 'ST058', name: 'Mr. M. Sivaraj' },
  { id: 'ST059', name: 'Dr. P. Mohan' },
  { id: 'ST060', name: 'Dr. A. Themozhi' },
  { id: 'ST061', name: 'Dr. S. Semmalar' },
  { id: 'ST062', name: 'Mr. D. Poobalan' },
  { id: 'ST063', name: 'Mr. R. Goutham Govind Raju' },
  { id: 'ST064', name: 'Dr. K. Sedhuraman' },
  { id: 'ST065', name: 'Mr. D. Balaji' },
  { id: 'ST066', name: 'Mr. S. Rajkumar' },
  { id: 'ST067', name: 'Mr. J. Vijayaraghavan' },
  { id: 'ST068', name: 'Mr. P. Sivasankar' },
  { id: 'ST069', name: 'Mr. V. Kumaraguru' },
  { id: 'ST070', name: 'Mrs. Sherly Metilda Dennis' },
  { id: 'ST071', name: 'Mr. U. Murugananthan' },
  { id: 'ST072', name: 'Mrs. K. C. Nithyasree' },
  { id: 'ST073', name: 'Mrs. T. Sudha' },
  { id: 'ST074', name: 'Mrs. D. Dharani' },
  { id: 'ST075', name: 'Mrs. S. Ramya' },
  { id: 'ST076', name: 'Mr. A. Baskaran' },
  { id: 'ST077', name: 'Dr. R. Baghya Nisha' },
  { id: 'ST078', name: 'Dr. A. Bargavi @ Meanachi' },
  { id: 'ST079', name: 'Dr. T. Radhika' },
  { id: 'ST080', name: 'Ms. S. Meenambigai' },
  { id: 'ST081', name: 'Mr. Vimal H' },
  { id: 'ST082', name: 'Dr. D. Tiroutchelvame' },
  { id: 'ST083', name: 'MR. S. GANESHKUMAR' },
]
