import type { StaffMember, TimetableSetup } from './models'
import type { GeneratedSection } from './scheduler'
import type { TeacherTimetable } from './teacher-timetable'
import { teacherTimetableDays, teacherTimetablePeriods } from './teacher-timetable.ts'

export const TEACHER_EXPORT_GENERATOR = 'mvit-college-timetable-generator'
export const TEACHER_EXPORT_VERSION = '1.0.0'
export const TEACHER_EXPORT_ORIGIN = 'This file was generated by the College Timetable Generator.'
const METADATA_NAMESPACE = 'https://mvit.edu/college-timetable-generator/ns/1.0/'
const PNG_KEYWORD = 'MVITTeacherTimetable'
const JPEG_XMP_HEADER = new TextEncoder().encode('http://ns.adobe.com/xap/1.0/\0')
export const teacherExportDepartmentNames: Record<string, string> = {
  CSE: 'Computer Science & Engineering',
  MECH: 'Mechanical Engineering',
  IT: 'Information Technology',
  AIML: 'Artificial Intelligence & Machine Learning',
  ECE: 'Electronics & Communication Engineering',
  EEE: 'Electrical & Electronics Engineering',
  IOT: 'Internet of Things',
  RA: 'Robotics & Automation',
  FT: 'Food Technology',
}

export interface TeacherExportAssignment {
  day: string
  period: number
  subjectOrActivity: string
  abbreviation: string
  code: string
  kind: string
  section: string
  teacherId: string
  teacherName: string
  departmentId: string
  departmentName: string
  year: string
  semester: string
}

export interface TeacherExportPayload {
  schemaVersion: 1
  generator: { id: string; version: string }
  originMarker: string
  sourceType: 'Teacher-wise Timetable'
  generationId: string
  exportId: string
  exportedAt: string
  teacherId: string
  teacherName: string
  departmentId: string
  departmentName: string
  academicYear: string
  year: string
  semester: string
  sectionList: string[]
  assignments: TeacherExportAssignment[]
  integrity: { algorithm: 'SHA-256'; digest: string }
}

export function teacherExportSourceKey(payload: Pick<TeacherExportPayload, 'generationId' | 'departmentId' | 'academicYear' | 'year' | 'semester' | 'sectionList'>): string {
  return [
    payload.generationId,
    payload.departmentId,
    payload.academicYear,
    payload.year,
    payload.semester,
    [...(payload.sectionList ?? [])].sort().join(','),
  ].join('\u0000')
}

function normalizeAcademicYear(value: string): string {
  return value.replace(/\s*[-–—]\s*/g, '-')
}

function normalizeYear(value: string): string {
  return /3rd/i.test(value) ? '3rd Year' : /2nd/i.test(value) ? '2nd Year' : value.split('/').at(-1)?.trim() || value
}

function normalizeSemester(value: string): string {
  return /odd|\b5th\b|\b7th\b/i.test(value) ? 'Odd' : /even|\b4th\b|\b6th\b|\b8th\b/i.test(value) ? 'Even' : value.split('/').at(-1)?.trim() || value
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = ''
  const chunkSize = 0x8000
  for (let start = 0; start < bytes.length; start += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(start, start + chunkSize))
  }
  return btoa(binary)
}

function base64ToBytes(value: string): Uint8Array {
  const binary = atob(value)
  return Uint8Array.from(binary, (character) => character.charCodeAt(0))
}

async function sha256(value: string): Promise<string> {
  if (!globalThis.crypto?.subtle) throw new Error('Secure SHA-256 metadata is unavailable in this browser.')
  const digest = await globalThis.crypto.subtle.digest('SHA-256', new TextEncoder().encode(value))
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}

function createExportId(): string {
  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID()
  const random = new Uint8Array(16)
  globalThis.crypto.getRandomValues(random)
  return [...random].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}

function canonicalCellData(sections: GeneratedSection[]): unknown[] {
  return sections.flatMap((section) => teacherTimetableDays.flatMap((day) => teacherTimetablePeriods.flatMap((period) => {
    const cell = section.schedule[day]?.[period]
    return cell ? [{ section: section.sectionId, day, period, itemId: cell.itemId, code: cell.code, abbreviation: cell.abbreviation, name: cell.name, teacherId: cell.teacherId, kind: cell.kind }] : []
  })))
}

export async function buildTeacherExportPayload(input: {
  setup: TimetableSetup
  teacher: StaffMember
  generatedSections: GeneratedSection[]
  timetable: TeacherTimetable
  exportedAt?: string
  exportId?: string
}): Promise<TeacherExportPayload> {
  const { setup, teacher, generatedSections, timetable } = input
  const departmentId = setup.academic.department
  const departmentName = teacherExportDepartmentNames[departmentId] ?? departmentId
  const year = normalizeYear(setup.academic.year)
  const semester = normalizeSemester(setup.academic.semester)
  const assignments: TeacherExportAssignment[] = teacherTimetableDays.flatMap((day) => teacherTimetablePeriods.flatMap((period) =>
    (timetable[day][period] ?? []).map(({ sectionId, cell }) => ({
      day,
      period,
      subjectOrActivity: cell.name,
      abbreviation: cell.abbreviation,
      code: cell.code,
      kind: cell.kind,
      section: sectionId,
      teacherId: cell.teacherId,
      teacherName: setup.staff.find((person) => person.id === cell.teacherId)?.name ?? cell.teacherId,
      departmentId,
      departmentName,
      year,
      semester,
    })),
  ))

  // The generation id fingerprints all actual generated section cells, while the
  // assignment list below is the selected teacher's exact visible projection.
  const generationDigest = await sha256(JSON.stringify(canonicalCellData(generatedSections)))
  const unsigned: Omit<TeacherExportPayload, 'integrity'> = {
    schemaVersion: 1,
    generator: { id: TEACHER_EXPORT_GENERATOR, version: TEACHER_EXPORT_VERSION },
    originMarker: TEACHER_EXPORT_ORIGIN,
    sourceType: 'Teacher-wise Timetable',
    generationId: `sha256:${generationDigest}`,
    exportId: input.exportId ?? createExportId(),
    exportedAt: input.exportedAt ?? new Date().toISOString(),
    teacherId: teacher.id,
    teacherName: teacher.name,
    departmentId,
    departmentName,
    academicYear: normalizeAcademicYear(setup.academic.academicYear),
    year,
    semester,
    sectionList: generatedSections.map(({ sectionId }) => sectionId),
    assignments,
  }
  const digest = await sha256(JSON.stringify(unsigned))
  return { ...unsigned, integrity: { algorithm: 'SHA-256', digest } }
}

export function createTeacherExportXmp(payload: TeacherExportPayload): string {
  const encodedPayload = bytesToBase64(new TextEncoder().encode(JSON.stringify(payload)))
  return `<?xpacket begin="\uFEFF" id="W5M0MpCehiHzreSzNTczkc9d"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="${TEACHER_EXPORT_GENERATOR} ${TEACHER_EXPORT_VERSION}"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:mvit="${METADATA_NAMESPACE}" mvit:origin="${escapeXml(TEACHER_EXPORT_ORIGIN)}" mvit:sourceType="Teacher-wise Timetable" mvit:payload="${encodedPayload}" mvit:integrityAlgorithm="SHA-256" mvit:integrityDigest="${payload.integrity.digest}"/></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>`
}

export function extractTeacherMetadataFromXmp(xml: string): TeacherExportPayload | null {
  const match = xml.match(/mvit:payload="([^"]+)"/)
  if (!match) return null
  const payload = JSON.parse(new TextDecoder().decode(base64ToBytes(match[1]))) as TeacherExportPayload
  const origin = xml.match(/mvit:origin="([^"]*)"/)?.[1]
  const sourceType = xml.match(/mvit:sourceType="([^"]*)"/)?.[1]
  const algorithm = xml.match(/mvit:integrityAlgorithm="([^"]*)"/)?.[1]
  const digest = xml.match(/mvit:integrityDigest="([^"]*)"/)?.[1]
  if (
    origin !== TEACHER_EXPORT_ORIGIN || sourceType !== 'Teacher-wise Timetable' ||
    algorithm !== 'SHA-256' || digest !== payload.integrity?.digest
  ) throw new Error('The XMP Teacher-wise Timetable markers are missing or inconsistent.')
  return payload
}

export function extractTeacherMetadataFromPdf(pdf: Uint8Array): TeacherExportPayload | null {
  if (pdf.length < 8 || new TextDecoder('latin1').decode(pdf.subarray(0, 5)) !== '%PDF-') {
    throw new Error('The PDF file could not be read.')
  }
  const source = new TextDecoder('latin1').decode(pdf)
  if (!source.includes('%%EOF')) throw new Error('The PDF file could not be read.')
  const start = source.indexOf('<x:xmpmeta')
  if (start < 0) return null
  const close = '</x:xmpmeta>'
  const end = source.indexOf(close, start)
  if (end < 0) throw new Error('The PDF teacher timetable metadata is malformed.')
  const payload = extractTeacherMetadataFromXmp(source.slice(start, end + close.length))
  if (!payload) throw new Error('The PDF teacher timetable metadata is malformed.')
  return payload
}

function escapeXml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll("'", '&apos;')
}

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff
  for (const byte of bytes) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0)
  }
  return (crc ^ 0xffffffff) >>> 0
}

function writeUint32(bytes: Uint8Array, offset: number, value: number): void {
  new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).setUint32(offset, value, false)
}

function readUint32(bytes: Uint8Array, offset: number): number {
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getUint32(offset, false)
}

function makePngChunk(type: string, data: Uint8Array): Uint8Array {
  const typeBytes = new TextEncoder().encode(type)
  const chunk = new Uint8Array(12 + data.length)
  writeUint32(chunk, 0, data.length)
  chunk.set(typeBytes, 4)
  chunk.set(data, 8)
  writeUint32(chunk, 8 + data.length, crc32(chunk.subarray(4, 8 + data.length)))
  return chunk
}

export function embedTeacherMetadataInPng(png: Uint8Array, payload: TeacherExportPayload): Uint8Array {
  const signature = [137, 80, 78, 71, 13, 10, 26, 10]
  if (png.length < 20 || signature.some((byte, index) => png[index] !== byte)) throw new Error('The teacher timetable PNG could not be prepared for metadata.')
  const keyword = new TextEncoder().encode(PNG_KEYWORD)
  const text = new TextEncoder().encode(JSON.stringify(payload))
  const itxt = new Uint8Array(keyword.length + 5 + text.length)
  itxt.set(keyword, 0)
  // Keyword NUL, uncompressed flag/method, empty language tag NUL, empty translated keyword NUL.
  itxt.set([0, 0, 0, 0, 0], keyword.length)
  itxt.set(text, keyword.length + 5)
  const metadataChunk = makePngChunk('iTXt', itxt)
  let offset = 8
  while (offset + 12 <= png.length) {
    const length = readUint32(png, offset)
    const type = new TextDecoder().decode(png.subarray(offset + 4, offset + 8))
    if (length > png.length - offset - 12) throw new Error('The teacher timetable PNG contains malformed data.')
    if (readUint32(png, offset + 8 + length) !== crc32(png.subarray(offset + 4, offset + 8 + length))) throw new Error('The teacher timetable PNG contains a damaged chunk.')
    if (type === 'IEND') {
      const result = new Uint8Array(png.length + metadataChunk.length)
      result.set(png.subarray(0, offset), 0)
      result.set(metadataChunk, offset)
      result.set(png.subarray(offset), offset + metadataChunk.length)
      return result
    }
    offset += 12 + length
  }
  throw new Error('The teacher timetable PNG is missing its end marker.')
}

export function extractTeacherMetadataFromPng(png: Uint8Array): TeacherExportPayload | null {
  const signature = [137, 80, 78, 71, 13, 10, 26, 10]
  if (png.length < signature.length || signature.some((byte, index) => png[index] !== byte)) {
    throw new Error('The PNG file could not be read.')
  }
  let offset = 8
  let foundEnd = false
  while (offset + 12 <= png.length) {
    const length = readUint32(png, offset)
    const type = new TextDecoder().decode(png.subarray(offset + 4, offset + 8))
    if (length > png.length - offset - 12) throw new Error('Malformed PNG chunk.')
    if (readUint32(png, offset + 8 + length) !== crc32(png.subarray(offset + 4, offset + 8 + length))) throw new Error('PNG chunk checksum does not match.')
    if (type === 'iTXt') {
      const data = png.subarray(offset + 8, offset + 8 + length)
      const separator = data.indexOf(0)
      if (separator >= 0 && new TextDecoder().decode(data.subarray(0, separator)) === PNG_KEYWORD) {
        if (data[separator + 1] !== 0 || data[separator + 2] !== 0) throw new Error('Unsupported compressed teacher metadata.')
        const textStart = separator + 5
        return JSON.parse(new TextDecoder().decode(data.subarray(textStart))) as TeacherExportPayload
      }
    }
    if (type === 'IEND') {
      if (length !== 0) throw new Error('Malformed PNG end marker.')
      foundEnd = true
      break
    }
    offset += 12 + length
  }
  if (!foundEnd) throw new Error('The PNG file could not be read.')
  return null
}

export function embedTeacherMetadataInJpeg(jpeg: Uint8Array, payload: TeacherExportPayload): Uint8Array {
  if (jpeg.length < 4 || jpeg[0] !== 0xff || jpeg[1] !== 0xd8) throw new Error('The teacher timetable JPG could not be prepared for metadata.')
  const xmp = new TextEncoder().encode(createTeacherExportXmp(payload))
  const segmentData = new Uint8Array(JPEG_XMP_HEADER.length + xmp.length)
  segmentData.set(JPEG_XMP_HEADER, 0)
  segmentData.set(xmp, JPEG_XMP_HEADER.length)
  const segmentLength = segmentData.length + 2
  if (segmentLength > 0xffff) throw new Error('The teacher timetable JPG metadata is too large.')
  const segment = new Uint8Array(segmentData.length + 4)
  segment.set([0xff, 0xe1, segmentLength >>> 8, segmentLength & 0xff], 0)
  segment.set(segmentData, 4)
  const result = new Uint8Array(jpeg.length + segment.length)
  result.set(jpeg.subarray(0, 2), 0)
  result.set(segment, 2)
  result.set(jpeg.subarray(2), 2 + segment.length)
  return result
}

export function extractTeacherMetadataFromJpeg(jpeg: Uint8Array): TeacherExportPayload | null {
  let offset = 2
  while (offset + 4 <= jpeg.length && jpeg[offset] === 0xff) {
    const marker = jpeg[offset + 1]
    if (marker === 0xda || marker === 0xd9) return null
    const segmentLength = (jpeg[offset + 2] << 8) | jpeg[offset + 3]
    if (segmentLength < 2 || offset + 2 + segmentLength > jpeg.length) throw new Error('Malformed JPEG segment.')
    const dataStart = offset + 4
    const data = jpeg.subarray(dataStart, offset + 2 + segmentLength)
    if (marker === 0xe1 && data.length >= JPEG_XMP_HEADER.length && JPEG_XMP_HEADER.every((byte, index) => data[index] === byte)) {
      const xml = new TextDecoder().decode(data.subarray(JPEG_XMP_HEADER.length))
      const payload = extractTeacherMetadataFromXmp(xml)
      if (!payload) throw new Error('The JPEG teacher timetable metadata is malformed.')
      return payload
    }
    offset += 2 + segmentLength
  }
  return null
}

export async function verifyTeacherExportPayload(payload: TeacherExportPayload): Promise<boolean> {
  return (await validateTeacherExportPayload(payload)).valid
}

export type TeacherExportPayloadValidation =
  | { valid: true; payload: TeacherExportPayload }
  | { valid: false; reason: string }

const supportedSemesters = new Set(['Odd', 'Even'])
const validDays = new Set<string>(teacherTimetableDays)

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0
}

export async function validateTeacherExportPayload(value: unknown): Promise<TeacherExportPayloadValidation> {
  if (!isRecord(value)) return { valid: false, reason: 'Timetable metadata is missing or invalid.' }
  if (value.sourceType !== 'Teacher-wise Timetable') {
    return { valid: false, reason: 'This file is not a Teacher-wise Timetable generated by the application.' }
  }
  const generator = isRecord(value.generator) ? value.generator : null
  if (generator?.id !== TEACHER_EXPORT_GENERATOR || generator?.version !== TEACHER_EXPORT_VERSION) {
    return { valid: false, reason: 'This file is not a Teacher-wise Timetable generated by the application.' }
  }
  if (value.originMarker !== TEACHER_EXPORT_ORIGIN) {
    return { valid: false, reason: 'The timetable origin marker is invalid.' }
  }
  if (value.schemaVersion !== 1) return { valid: false, reason: 'Timetable metadata uses an unsupported schema.' }
  if (!isNonEmptyString(value.teacherId) || !isNonEmptyString(value.teacherName)) {
    return { valid: false, reason: 'Teacher identity is missing from the timetable metadata.' }
  }
  if (!isNonEmptyString(value.departmentId) || !isNonEmptyString(value.departmentName)) {
    return { valid: false, reason: 'Department metadata is missing.' }
  }
  const expectedDepartmentName = teacherExportDepartmentNames[value.departmentId] ?? value.departmentId
  if (value.departmentName !== expectedDepartmentName) {
    return { valid: false, reason: 'Department metadata is inconsistent.' }
  }
  if (!isNonEmptyString(value.academicYear) || !/^\d{4}-\d{4}$/.test(value.academicYear)) {
    return { valid: false, reason: 'Academic year metadata is missing or invalid.' }
  }
  if (!isNonEmptyString(value.year)) {
    return { valid: false, reason: 'Academic year level metadata is missing or invalid.' }
  }
  if (!isNonEmptyString(value.semester) || !supportedSemesters.has(value.semester)) {
    return { valid: false, reason: 'Semester metadata is missing or invalid.' }
  }
  if (!isNonEmptyString(value.generationId) || !/^sha256:[a-f0-9]{64}$/.test(value.generationId)) {
    return { valid: false, reason: 'The generated schedule fingerprint is missing or invalid.' }
  }
  if (!isNonEmptyString(value.exportId) || !isNonEmptyString(value.exportedAt) || !Number.isFinite(Date.parse(value.exportedAt))) {
    return { valid: false, reason: 'Export metadata is missing or invalid.' }
  }
  if (!Array.isArray(value.sectionList) || value.sectionList.length === 0 || value.sectionList.some((section) => !isNonEmptyString(section))) {
    return { valid: false, reason: 'The source timetable metadata is malformed.' }
  }
  if (!Array.isArray(value.assignments)) return { valid: false, reason: 'The source schedule payload is missing or invalid.' }
  for (const assignment of value.assignments) {
    if (!isRecord(assignment) || !validDays.has(String(assignment.day)) ||
      !Number.isInteger(assignment.period) || !teacherTimetablePeriods.includes(assignment.period as number) ||
      !isNonEmptyString(assignment.subjectOrActivity) || typeof assignment.abbreviation !== 'string' ||
      typeof assignment.code !== 'string' || !isNonEmptyString(assignment.kind) || !isNonEmptyString(assignment.section) ||
      !value.sectionList.includes(assignment.section) || assignment.teacherId !== value.teacherId ||
      assignment.teacherName !== value.teacherName || assignment.departmentId !== value.departmentId ||
      assignment.departmentName !== value.departmentName || assignment.year !== value.year ||
      assignment.semester !== value.semester
    ) return { valid: false, reason: 'The source schedule payload is malformed or inconsistent.' }
  }
  if (!generator || !isRecord(value.integrity) || value.integrity.algorithm !== 'SHA-256' ||
    !isNonEmptyString(value.integrity.digest) || !/^[a-f0-9]{64}$/.test(value.integrity.digest)
  ) return { valid: false, reason: 'The timetable integrity metadata is missing or invalid.' }

  const payload = value as unknown as TeacherExportPayload
  const { integrity, ...unsigned } = payload
  try {
    if (await sha256(JSON.stringify(unsigned)) !== integrity.digest) {
      return { valid: false, reason: 'The timetable metadata integrity check failed.' }
    }
  } catch {
    return { valid: false, reason: 'Timetable metadata could not be verified in this browser.' }
  }
  return { valid: true, payload }
}
